---
- hosts: www

  vars:
    - root_dir: ..


  pre_tasks:
    - debug: msg="Pre tasks section"

  roles:
     - {
         role: "sa-postfix"
       }

     - {
        role: "sa-logwatch"

       }

  tasks:

    - debug: msg="Tasks section"



